# Training Curriculum 
# this yaml serves as container of the learning curriculum for the agent
# by determining the number of static/dynamic obstacles per stage
# (will carry on training on last stage when threshhold reached)

1:
  static: 0
  dynamic: 0
2:
  static: 0
  dynamic: 2
3:
  static: 1
  dynamic: 4
4:
  static: 2
  dynamic: 6
